services: 
  postgres: 
    image: postgres:latest
    restart: unless-stopped
    container_name: financial-management
    ports: 
    - 5434:5432
    environment:
      - POSTGRES_PASSWORD=bunKikiBackend
      - POSTGRES_USER=bunBackend
      - POSTGRES_DB=financialManagement